export const GAME_CONFIG = {
  BIRD_WIDTH: 34,
  BIRD_HEIGHT: 24,
  GRAVITY: 0.5,
  JUMP_STRENGTH: -10,
  PIPE_SPEED: 3,
  PIPE_SPAWN_RATE: 1500, // ms
  PIPE_WIDTH: 52,
  PIPE_GAP: 160,
  CANVAS_WIDTH: 400,
  CANVAS_HEIGHT: window.innerHeight,
  GROUND_HEIGHT: 90,
};
